NUMPY ONE DIMENSIONAL ARRAY :

In [4]:
import numpy as np
a = [1, 2, 3, 4, 5]
myarr = np.array(a)
print(myarr)
print(type(myarr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [15]:
import numpy as np
myarr = np.array([1, 2, 3, 4, 5],np.int64)
myarr1 = np.array([[1, 2, 3, 4, 5]],np.int64)
myarr

array([1, 2, 3, 4, 5], dtype=int64)

In [16]:
import numpy as np
myarr = np.array([1, 2, 3, 4, 5], np.int64)
myarr1 = np.array([[1, 2, 3, 4, 5]], np.int64)
myarr1[0,1]

2

In [17]:
import numpy as np
myarr = np.array([1, 2, 3, 4, 5], np.int64)
myarr1 = np.array([[1, 2, 3, 4, 5]], np.int64)
myarr1.shape

(1, 5)

In [18]:
import numpy as np
myarr = np.array([1, 2, 3, 4, 5], np.int64)
myarr.dtype


dtype('int64')

In [24]:
import numpy as np
myarr = np.array([1, 2, 3, 4, 5], np.int64)
myarr1 = np.array([[1, 2, 3, 4, 5]], np.int64)
myarr1.size

5

In [23]:
np.array({35,25,15})

array({25, 35, 15}, dtype=object)

In [22]:
zeros=np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
rng=np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
lspace=np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [30]:
emp=np.empty((4,6))
emp

array([[6.69393515e-312, 6.76869935e-322, 0.00000000e+000,
        0.00000000e+000, 6.68428674e-312, 5.30276956e+180],
       [6.00736842e-067, 4.95296723e+097, 6.76090322e-067,
        3.92481637e+126, 4.25223142e+180, 7.48543529e+247],
       [2.32363010e+251, 6.11130817e+223, 2.59903818e-144,
        2.25375651e+180, 3.88585878e-033, 4.71386151e-090],
       [4.00086278e+175, 2.59027861e-144, 1.16442250e-028,
        9.44872517e-143, 6.68579905e-312, 2.08667532e-308]])

NUMPY ONE DIMENSIONAL ARRAY USER INPUT :

In [20]:
import numpy as np
a = []
n = int(input("Enter the size of thé array :"))
for i in range(n):
    val = int(input("Enter the number : "))
    a.append(val)
myarray = np.array(a)
myarray

array([1, 2, 3, 4, 5])