In [5]:
import numpy as np
l=[10,20,30,40,50,60]
print(l[2:5])
print(l[2:])
print(l[:5])
print(l[:])
print(l[3:6:2])
print()
print(l[5:1:-1])
print(l[5:0])
print(l[-2:-1:-1])

[30, 40, 50]
[30, 40, 50, 60]
[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50, 60]
[40, 60]

[60, 50, 40, 30]
[]
[]


In [9]:
#SLICE OPERATOR ON 2D ARRAY

a=np.array([[12,35],[45,62],[85,65]])
print(a.shape)
a


(3, 2)


array([[12, 35],
       [45, 62],
       [85, 65]])

In [31]:
print(a[:,0:1])
print()
print(a[0:2,0:2])
print()
print(a[::2,:])

[[12]
 [45]
 [85]]

[[12 35]
 [45 62]]
[[12 35]
 [85 65]]


In [37]:
l=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,160]]
a=np.array(l)
print(a)
print()
print(a[::3,:])
print()
print(a[:,::2])
print()
print(a[1:3,1:3])
print()
print(a[1:3])

[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 13  14  15 160]]

[[  1   2   3   4]
 [ 13  14  15 160]]

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]

[[ 6  7]
 [10 11]]

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [47]:
#slice on 3d array
l = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16],[17,18,19,20],[21,22,23,24]]]
a=np.array(l)
print(a)
print(a)
print(a.shape)
print()
print(a[:,:,:1])
print()
print(a[:,2:,:])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(2, 3, 4)

[[[ 1]
  [ 5]
  [ 9]]

 [[13]
  [17]
  [21]]]

[[[ 9 10 11 12]]

 [[21 22 23 24]]]
