In [1]:
# TO FIND MEAN
a,b,c,d,e=20,2,7,1,34
mean=(a+b+c+d+e)/5
print(mean)

12.8


In [ ]:
# 3] PRINT MEAN OF SINGLE LIST
import numpy as np
l1=[20,2,7,1,34]
mean=np.mean(l1)
print(mean)

12.8


In [ ]:
# 4] PRINT MATRIX
import numpy as np
num=[[20,2,7,1,34],[15,2,65,4,5],[5,4,85,95,65,]]
print(num)

[[20, 2, 7, 1, 34], [15, 2, 65, 4, 5], [5, 4, 85, 95, 65]]


In [ ]:
# 5] MEAN
import numpy as np
arr=np.array([[14,17,12,33,44],[15,6,27,8,19],[23,2,54,1,4]])
print(arr)
mean=np.mean(arr)
print(mean)
mean1=np.mean(arr[0])
print(mean1)
mean2=np.mean(arr[1])
print(mean2)
mean3=np.mean(arr[2])
print(mean3)
y=np.mean(arr,axis=1)
print(y)
y2=np.mean(arr,axis=0)
print(y2)

[[14 17 12 33 44]
 [15  6 27  8 19]
 [23  2 54  1  4]]
18.6
24.0
15.0
16.8
[24.  15.  16.8]
[17.33333333  8.33333333 31.         14.         22.33333333]


In [ ]:
# 6] MAXIMUM AND MINIMUM , RANGE
num=[[20,2,7,1,34],[15,2,65,4,5],[5,4,85,95,65,]]
import numpy as np
m1=np.max(num,axis=None)
print(m1)
m2=np.min(num,axis=None)
print(m2)
r1=m1-m2
print(r1)

95
1
94


In [ ]:
# 6] Mean, Median, Mode
import statistics as st
spd=[99,86,87,88,111,86,103,87,94,78,77,85,86]
mean=st.mean(spd)
print(mean)
mode=st.mode(spd)
print(mode)
median=st.median(spd)
print(median)

89.76923076923077
86
87


In [ ]:
# 7]  GEOMETRIC MEAN
from scipy.stats import  gmean
c=[[1,3,27],[3,4,6],[7,6,3],[3,6,8]]
mean=gmean(c)
print(mean)

[2.81731325 4.55901411 7.89644408]


In [20]:
# 8] MEAN , MEDIAN , MODE OF THE GIVEN FREQUENCY 
import statistics as st
import numpy as np
L=[[0,1,2,3,4,5,6],[0.99,1.99,2.99,3.99,4.99,5.99,6.99]]
MidP=np.mean(L,axis=0)
Frq=[2,4,6,7,5,3,1]
Mean_MidP=np.average(MidP,weights=Frq)
print("Mean is ",round(Mean_MidP,4))

Mean is  3.2807


In [ ]:
# 9]  PERCENTILE
p=[30,40,72,83,25,10,50,90,60,15,90,60,15,5,9,34,23,67,80]
import numpy as np
#to find 30th percentile
p30=np.percentile(p,30)
print("30th percentile is ",p30)
#to find 50th percentile
p50=np.percentile(p,50)
print("50th percentile is ",p50)
#to find 75th percentile
p75=np.percentile(p,75)
print("75th percentile is ",p75)
p90=np.percentile(p,90)
print("90th percentile is ",p90)

30th percentile is  23.799999999999997
50th percentile is  40.0
75th percentile is  69.5
90th percentile is  84.39999999999999


In [ ]:
# 10] STANDARD DEVIATION
heights=[51,38,79,46,57]
import numpy as np
SD=np.std(heights)
print("standard deviation is ",round(SD,4))

standard deviation is  13.8766


In [ ]:
# 11] chef : SD AND MEAN
Q=(6.3,7.2,7.3,8.1,7.8,6.8,7.5,7.8,7.5,7.2,8.2,8.0,7.4,7.6,7.7,7.6,7.7,7.6,7.4,7.5,8.4,7.4,7.6,6.2,7.4,)
import numpy as np 
mean_Q =np.mean(Q)
sd_Q =np.std(Q)
print("Mean = ",mean_Q)
print("STANDARD DEVIATION = ",round(sd_Q,1))

Mean =  7.4879999999999995
STANDARD DEVIATION =  0.5


In [ ]:
# 12] 
import numpy as np
Mean_GA =32.11
Var_GA =68.09
SD_GA =np.sqrt(Var_GA)
Mean_GB =19.75
Var_GB = 71.14
SD_GB = np.sqrt(Var_GB)
CV_A = Mean_GA/SD_GA
print(round(CV_A,2))
CV_B=Mean_GB/SD_GB
print(round(CV_B,2))

3.89
2.34
